# Generated by Django 5.2.6 on 2025-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenId', models.CharField(max_length=50)),
                ('chainName', models.CharField(max_length=10)),
                ('contractAddress', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('mulPoint', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('percentChange24h', models.CharField(max_length=50)),
                ('volume24h', models.CharField(max_length=50)),
                ('liquidity', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'alpha',
                'verbose_name_plural': 'alpha',
                'db_table': 'alpha',
            },
        ),
    ]
